apiVersion: apps/v1
kind: Deployment
metadata:
  name: campsite
  labels:
    app: campsite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: campsite
  template:
    metadata:
      labels:
        app: campsite
    spec:
      containers:
        - name: campsite
          image: soonchul/campsite:20230308
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/xxx/'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
